# Generated by Django 4.0.6 on 2022-07-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification_api', '0002_features_two_alter_features_one'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='one',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='features',
            name='two',
        ),
    ]
